#!/usr/bin/env ruby
# Copyright 2011-2012 Fred Emmott. See COPYING file.

$LOAD_PATH.push File.dirname(__FILE__) + '/../lib'
$LOAD_PATH.push File.dirname(__FILE__) + '/./gen-rb'
require 'my_stuff/fb303/server'
require 'echo_service'

class EchoHandler
  def echo string
    puts string
  end
end

class EchoServer < MyStuff::Fb303::Server
  def initialize
    super EchoService, 'Echo Service'
  end

  def handler
    @handler ||= EchoHandler.new
  end

  def server_for processor
    socket    = Thrift::ServerSocket.new 9090
    transport = Thrift::FramedTransportFactory.new
    protocol  = Thrift::BinaryProtocolFactory.new
    Thrift::SimpleServer.new(
      processor,
      socket,
      transport,
      protocol
    )
  end
end

if File.expand_path($0) == File.expand_path(__FILE__)
  EchoServer.new.run!
end
